#!/bin/bash

cd ..

wget "https://www.wiley.com//college/kuby/1118422570/compchact/ch01/inter.swf" -O "mainter.swf"
wget "https://www.wiley.com//college/kuby/1118422570/compchact/ch01/TControl.swf" -O "maTControl.swf"
wget "https://www.wiley.com//college/kuby/1118422570/compchact/ch01/gr.swf" -O "magr.swf"
wget "https://www.wiley.com//college/kuby/1118422570/compchact/ch01/gr2.swf" -O "magr2.swf"

for VARIABLE in {2..21}
do
	wget "https://www.wiley.com//college/kuby/1118422570/compchact/ch01/map$VARIABLE.swf" -O "mamap$VARIABLE.swf"
	wget "https://www.wiley.com//college/kuby/1118422570/compchact/ch01/map${VARIABLE}prew.swf" -O "mamap${VARIABLE}prew.swf"
done
